#@ load("@ytt:data", "data")

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-ingress-ns-role
  namespace: #@ data.values.namespace
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  #! Defaults to "<election-id>-<ingress-class>"
  #! Here: "<ingress-controller-leader>-<nginx>"
  #! This has to be adapted if you change either parameter
  #! when launching the nginx-ingress-controller.
  - "ingress-controller-leader-nginx"
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: nginx-ingress-ns-role-binding
  namespace: #@ data.values.namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-ingress-ns-role
subjects:
- kind: ServiceAccount
  name: nginx-ingress-sa
  namespace: #@ data.values.namespace
