#@ load("@ytt:template", "template")
#@ load("@ytt:overlay", "overlay")

#@ load("@github.com/k14s/k8s-lib:app/module.lib.yml", "app")

#@ hello_port = 80
#@ def hello_container():
image: hashicorp/http-echo
args:
- -listen=:(@= str(hello_port) @)
- -text=hellozzz!
#@ end

#@ def hello_changes():
#@overlay/match by=overlay.subset({"kind":"Ingress"})
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #!@overlay/match missing_ok=True
    #!nginx.ingress.kubernetes.io/temporal-redirect: https://www.google.com
    #!@overlay/match missing_ok=True
    #!nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    #!@overlay/match missing_ok=True
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

#@overlay/match by=overlay.subset({"kind":"HorizontalPodAutoscaler"})
---
spec:
  metrics:
  #@overlay/match by=overlay.subset({"resource":{"name":"cpu"}})
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 3
#@ end

#@ app_config = app.make("hello", hello_container(), namespace="default", port=hello_port).config()
#@ app_config = overlay.apply(app_config, hello_changes())
--- #@ template.replace(app_config)
