---
apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    simple-app: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      simple-app: ""
  template:
    metadata:
      labels:
        simple-app: ""
    spec:
      containers:
      - name: default
        image: simple-app-image
        ports:
        - containerPort: 8080
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: simple-app-image
  path: src/
